language: python
python:
	- '3.8'

before_script:
	- pip install pipenv
	- pipenv install --dev
	- psql -c 'create database travis_ci_test;' -U postgres

branches:
	only:
		- master

services:
	- postgresql

script:
	- ./manage.py test